name: Slack Notification on Project Card Move A

on:
  project_card:
    types:
      - created
      - edited
      - moved
      - deleted

permissions:
  project_card: write

jobs:
  slack_notification_a:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "text": "A project card has been moved",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Card URL: ${{ github.event.project_card.url }}"
                  }
                }
              ]
            }' \
            $SLACK_WEBHOOK_URL
